Server:
  RunMode: debug
  ServiceName: blog-server
  HttpPort: 4433
  ReadTimeout: 60
  WriteTimeout: 60
App:
  DefaultPageSize: 10
  MaxPageSize: 100
  LogSavePath: storage/logs
  LogFileName: app
  LogFileExt: .log
  LogMaxSize: 600
  LogMaxAge: 10
  LogLocalTime: true
  UploadSavePath: storage/uploads
  UploadServerUrl: http://127.0.0.1:4433/static
  UploadImageMaxSize: 5
  UploadImageAllowExts:
    - .jpg
    - .jpeg
    - .png
  UploadDocSavePath: storage/doc
  UploadDocServerUrl: http://127.0.0.1:4433/doc
  UploadDocMaxSize: 50
  UploadDocAllowExts:
    - .pdf
    - .word
    - .excel
  DefaultContextTimeout: 1
  AgentHostPort: 127.0.0.1:6831
DataBase:
  DBType: mysql
  Username: root
  Password: 123456
  Host: 127.0.0.1:3306
  DBName: blog
  TablePrefix: blog_
  Charset: utf8mb4
  ParseTime: True
  MaxIdleConns: 10
  MaxOpenConns: 30
JWT:
  Secret: eddycjy
  Issuer: blog
  Expire: 7200
Email:
  Host: smtp.qq.com
  Port: 465
  Username: 01@qq.com
  Password: xxxx
  IsSSL: true
  From: zzxx@qq.com
  To:
    - ccxxx@163.com

